# Generated by Django 5.1 on 2025-03-03 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('doctors', '0003_alter_doctor_contact_number_alter_doctor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Available', max_length=20),
        ),
    ]
